services:
  db:
    image: postgis/postgis:15-3.3
    container_name: fastapi_postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastapi_gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
